import Head from "next/head";

export async function getStaticPaths() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  const allPaths = [];
  
  posts.map(post => allPaths.push({params: { id: post.id.toString() }}));

  return {
    paths: allPaths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  const post = posts.find(x => x.id === Number(params.id));

  return {
    props: { post }
  }
}

export default function Post({ post }) {  
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{post.title}</h2>
      <p>{post.body}</p>
    </>
  )
}