import Head from "next/head";

export default function goodbyeWorld() {
  return (
    <>
      <Head>
        <title>Goodbye World!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Goodbye World!</h1>
    </>
  );
}